# Generated by Django 4.2.7 on 2025-11-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctorprofile',
            table='doctor_doctorprofile',
        ),
    ]
